### PR TITLE
Add gemmt symbols

### PR DESCRIPTION
**Pull request by amontoison**
https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/blas-and-sparse-blas-routines/blas-like-extensions/gemmt.html

### CODE REVIEW

**Comment by staticfloat** [comment]
I see that the latest MKL_jll release actually contains this symbol.  Can you please add a test case [within this testset](https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/95aef379019a3573430cbfc1c099c1f47e7eb175/test/direct.jl#L200) that first checks that `dgemmt()` has a mapping, and then directly calls `dgemmt()` with some arguments, to assert that it's properly working?

**Comment by amontoison** [comment]
@staticfloat I updated the PR but we can't test it with the CI build because `MKL_jll` is not available on FreeBSD.

**Comment by staticfloat** [comment]
I've altered the CI configuration, (previously everything except the FreeBSD tests refused to run on PRs from 3rd-party forks).  Can you rebase on latest `main` and try again?

**Comment by staticfloat** [comment]
I updated the test dependencies to get a newer version of `MKL_jll` in https://github.com/JuliaLinearAlgebra/libblastrampoline/pull/96, can you rebase and try again?

**Comment by amontoison** [comment]
> I updated the test dependencies to get a newer version of `MKL_jll` in #96, can you rebase and try again?

I rebased and I still have an undefined reference for `dgemmt_` with LBT.

**Comment by staticfloat** [comment]
Ah, of course, the new symbols aren't exported.  You need to run the [`ext/gensymbol/generate_func_list.sh`](https://github.com/JuliaLinearAlgebra/libblastrampoline/blob/main/ext/gensymbol/generate_func_list.sh) script.  That will write out new header files, which you need to commit in here as well.  The buildkite CI (which you should now be able to see, thank you for telling me it was still set to "private") [has a job](https://buildkite.com/julialang/libblastrampoline/builds/48#0184c514-7d25-471b-8ed3-0db40ef896ec/87-102) which outputs what the file should look like, if there is inconsistency between the source and generated header.

**Comment by amontoison** [comment]
All tests passed now, thanks @staticfloat!
`gemmt` will be available with the release 0.3.22 of OpenBLAS for information: https://github.com/xianyi/OpenBLAS/pull/3796

**Comment by staticfloat** [comment]
Great, so once that's released and packaged, we can update the tests here to use `gemmt` with OpenBLAS as well.  :)

**Pull request merged**
