### PR TITLE
Add new symbols for the future release of Reference-LAPACK

### PR DESCRIPTION
**Pull request by amontoison**
- The future official release of `BLAS` will contain the symbol `Xgemmtr`.
- Add `cblas_Xgemm_batch`.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Shouldn't this bump the version to 5.12, since new symbols were added?

**Comment by staticfloat** [comment]
Adding new symbols is, to my mind, more of a data change than a feature change.

**Comment by ViralBShah** [comment]
Ok, I was thinking these are APIs. In that any program that links against these new APIs will need a 5.11.2 lower bound, making it feel like a feature from a user perspective.

**Comment by giordano** [comment]
Yeah, lbt is a bit weird because it has its own API, and it also exposes other libraries' APIs, making thinking about semver complicated (whose API matters?)

**Comment by ViralBShah** [comment]
I feel like doing `nm libblastrampoline.so` gives me what I think of as the API. I think the user's API should drive the versioning here.

**Comment by staticfloat** [comment]
Fair enough. Let’s bump it forward.

**Comment by ViralBShah** [comment]
I think the simplest thing to do might just be to tag the same release as 5.12.0 (and let 5.11.2 be as is).

**Pull request merged**
