### PR TITLE
Fix build for OpenBSD

### PR DESCRIPTION
**Pull request by cmburn**
Adjust the macros to allow building on OpenBSD

### CODE REVIEW

**Comment by staticfloat** [comment]
Great!  What is your interest in OpenBSD?

Also, do you know of any CI systems that allow us to test on OpenBSD?

**Review by staticfloat — APPROVED** [review]

**Comment by cmburn** [comment]
Ah, just slowly but surely trying to get Julia working on OpenBSD! I run it on my laptop, and would like to try to replace Octave/remote MATLAB with Julia at some point. Sourcehut is the only CI I can think of that has full OpenBSD support, though I think they're looking at adding it for Cirrus.

**Comment by staticfloat** [comment]
Looks like they're actively working on it: https://github.com/cirruslabs/cirrus-ci-docs/issues/970

I'm going to merge this as-is for now, as I don't think these changes could possibly be _wrong_, but if you end up hearing about a free OpenBSD CI provider, please feel free to open a PR towards this repository, so that we can ensure that it keeps working.

**Comment by ararslan** [comment]
According to the now-closed thread Elliot linked, NetBSD now works on Cirrus. I just migrated our FreeBSD CI here to Cirrus, so we could try adding OpenBSD to our Cirrus setup.

**Pull request merged**
