### PR TITLE
Use Cirrus for FreeBSD CI rather than Travis

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
Opened an issue for the failing Windows CI: https://github.com/JuliaLinearAlgebra/libblastrampoline/issues/86

**Review by ViralBShah — APPROVED** [review]

**Comment by ararslan** [comment]
Also, I just noticed that the repository has setup files for Drone CI but it doesn't actually seem to be running Drone on PRs (or at all?).

**Comment by ViralBShah** [comment]
Probably remove them?

**Comment by ViralBShah** [comment]
@giordano seems to be the one who set up the Drone CI.

**Comment by ararslan** [comment]
If Drone is no longer usable for whatever reason, Cirrus supports Linux ARMv8 and I think Alpine Linux, so those could run alongside FreeBSD on Cirrus.

**Comment by giordano** [comment]
Yeah, I think Drone is shutting down their free servicing. I don't know any good free CI providers for arm nowadays

**Pull request merged**
