### PR TITLE
[CirrusCI] Run FreeBSD tests with Julia 1; add more platforms

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
dgemmt is failing also here on FreeBSD.  CC: @amontoison

**Comment by amontoison** [comment]
`gemmt` should be only tested with `MKL`.
`MKL` is not available on FreeBSD (we don't have a MKL_jll for this platform).

**Comment by amontoison** [comment]
@giordano The error with FreeBSD is for `dgemm` and not `dgemmt`, I am wrong?

**Comment by giordano** [comment]
Yeah, too similar names.  @ararslan how to install `gmake`?  The `make` available doesn't seem to like our makefiles.

**Comment by ararslan** [comment]
> how to install `gmake`?

`pkg update && pkg install -y gmake`

> The `make` available doesn't seem to like our makefiles.

Yeah, `make` on BSD is BSD Make, which is incompatible with GNU Make.

**Comment by ararslan** [comment]
Looks like you figured it out on your own 🙂

**Comment by giordano** [comment]
Yay, it's working!  I'm going to merge this, to have CI working on FreeBSD and Musl Linux.

**Pull request merged**
