### PR TITLE
Upgrade gensymbol

### LINKED ISSUE #120: Add new symbols for dynamic mode decomposition
LAPACK v3.12 contains new symbols.
They updated `gensymbol` in OpenBLAS (see [here](https://github.com/OpenMathLib/OpenBLAS/commit/174f4e65e320241c7b57136db95d367cac7583d7)) but not the Perl version `gensymbol.pl`.

### PR DESCRIPTION
**Pull request by amontoison**
close #120 
@staticfloat @giordano @ViralBShah 
Add symbols for LAPACK 3.10, 3.11 and 3.12.

### CODE REVIEW

**Comment by amontoison** [comment]
Can we do a new release 5.9.0?

**Comment by ViralBShah** [comment]
I'll be able to get to it in a couple of days - but @amontoison do you have rights to tag packages in this org?

**Comment by amontoison** [comment]
No, I only have the rights on JuliaSparse.

**Comment by ViralBShah** [comment]
I just tagged the release, and also invited you to the org.

**Comment by amontoison** [comment]
@ViralBShah Thanks Viral!
I will compile it with Yggdrasil.

**Pull request merged**
